import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import NavBar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";
import { AppProvider } from "@/context/AppContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import Container from "react-bootstrap/Container";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AppProvider>
          <NavBar />
          <Container>{children}</Container>
          <Footer />
        </AppProvider>
      </body>
    </html>
  );
}
