import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import NavBar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";
import { AppProvider } from "@/context/AppContext";
import AuthProvider from "@/components/Auth/AuthProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import Container from "react-bootstrap/Container";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AppProvider>
          <AuthProvider>
            <NavBar />
            <Container>{children}</Container>
            <Footer />
          </AuthProvider>
        </AppProvider>
      </body>
    </html>
  );
}
